name: OpenACR editor cypress testing

on:
  pull_request:

jobs:
  build-test:
    name: Building app, run app and tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source.
        uses: actions/checkout@v4

      - name: Install dependencies.
        run: npm ci

      - name: Build app.
        run: export NODE_ENV=development && npm run build

      - name: Run app.
        run: export NODE_ENV=development && npm run dev &

      - name: Run tests
        run: npm test

      - name: Archive test results.
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-results
          path: cypress/results
          retention-days: 2
